config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  get 'profile/show'
  resources :comments
  resources :votes
  devise_for :users
  root 'restaurants#index', as: 'restaurants_index'

  resources :restaurants do
    post 'vote', on: :member
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[show]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.new
    @comment.user_id = current_user.id
    @comment.restaurant_id = @restaurant.id
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to profile_show_path, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :restaurant_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= comment.user.email %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Restaurant:</strong>
    <%= comment.restaurant.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= comment.content %>
  </p>


  <% if action_name != "show" %>
    <%= link_to "Show this comment", comment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/comments/_comment_table.html.erb
<% comments.each do |comment| %>
  <tr>
    <td class="border p-2">
      <% if profile %>
        <%= comment.restaurant.name %>
      <% else %>
        <%= comment.user.email%>
      <% end %>
    </td>
    <td class="border p-2"><%= comment.content%></td>
    <td class="border p-2 text-center">
      <% if profile %>
        <div class="flex justify-center">
          <%= button_to "Delete this comment", comment_path(comment), method: :delete, class: "format-button mr-2" %>
          <%= link_to "View restaurant", restaurant_path(comment.restaurant.id) , class: "format-button" %>
        </div>
      <% else %>
        <%= link_to "Show", comment, class: "format-button" %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_email %>
    <%= form.text_field :user_email, value: comment.user.email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full  #{'readonly-style' if readonly}", readonly: readonly %>
    <%= form.hidden_field :user_id, value: comment.user.id %>
  </div>

  <div class="my-5">
    <%= form.label :restaurant_name %>
    <%= form.text_field :restaurant_name, value: comment.restaurant.name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{'readonly-style' if readonly}", readonly: readonly %>
    <%= form.hidden_field :restaurant_id, value: comment.restaurant.id %>
  </div>

  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_field :content, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "format-button" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing comment</h1>

  <%= render "form", comment: @comment %>

  <%= link_to "Show this comment", @comment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to comments", comments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/comments/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Comments</h1>
    <%= link_to "New comment", new_comment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="comments" class="min-w-full">
    <%= render @comments %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New comment</h1>

  <%= render "form", comment: @comment, readonly: true %>

  <%= link_to "Back to restaurant", restaurant_path(@restaurant.id) , class: "format-button" %>
</div>

app/views/comments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <h2 class="font-bold text-4xl">Viewing Comment</h2>


    <%= render @comment %>

    <!-- <%= link_to "Edit this comment", edit_comment_path(@comment), class: "format-button" %>
      <div class="inline-block ml-2">
        <%= button_to "Destroy this comment", comment_path(@comment), method: :delete, class: "format-button" %>
      </div>
    -->
    <%= link_to "Back to restaurant", restaurant_path(@comment.restaurant.id) , class: "format-button" %>
  </div>
</div>