config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  get 'profile/show'
  resources :comments
  resources :votes
  devise_for :users
  root 'restaurants#index', as: 'restaurants_index'

  resources :restaurants do
    post 'vote', on: :member
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :votes
  has_many :comments
  has_many :favorites

  before_validation :set_defaults, on: :create

  validates :name, :location, :will_split, :wont_split, presence: true
  validates :name, uniqueness: { scope: :location, message: "has already been taken at this location." }

  def set_defaults
    self.will_split = 0 if will_split.blank?
    self.wont_split = 0 if wont_split.blank?
  end

  def vote(split_check)
    if split_check
      increment!(:will_split)
    else
      increment!(:wont_split)
    end
  end

  def self.search(search)
    if search
      @restaurants = Restaurant.where("name LIKE :search OR location LIKE :search", search: "%#{search}%")
    else
      @restaurants = Restaurant.all
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :set_restaurant, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[index show]

  def vote
    @restaurant = Restaurant.find(params[:id])
    vote_value = params[:vote] == 'true'

    if current_user
      @vote = current_user.votes.find_or_initialize_by(restaurant: @restaurant)
      @vote.update(vote: vote_value)

      update_vote_counts(@restaurant)
    end
  end

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.search(params[:search])
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to restaurant_url(@restaurant), notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy

    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :will_split, :wont_split)
    end

    def update_vote_counts(restaurant)
      restaurant.update(
        will_split: restaurant.votes.where(vote: true).count,
        wont_split: restaurant.votes.where(vote: false).count
      )
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, class: "contents") do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{'readonly-style' if readonly}", readonly: readonly %>
  </div>

  <div class="my-5">
    <%= form.label :location %>
    <%= form.text_field :location, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{'readonly-style' if readonly}", readonly: readonly %>
  </div>

  <% if action_name.in?(['show']) %>
    <div class="my-5">
      <%= form.label :will_split %>
      <%= form.number_field :will_split, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{'readonly-style' if readonly}", readonly: readonly %>
    </div>

    <div class="my-5">
      <%= form.label :wont_split %>
      <%= form.number_field :wont_split, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{'readonly-style' if readonly}", readonly: readonly %>
    </div>
  <% end %>

  <% unless readonly %>
    <div class="inline">
      <%= form.submit class: "format-button" %>
    </div>
  <% end %>
<% end %>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= restaurant.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Location:</strong>
    <%= restaurant.location %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Will split:</strong>
    <%= restaurant.will_split %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Wont split:</strong>
    <%= restaurant.wont_split %>
  </p>

</div>

app/views/restaurants/_restaurant_table.html.erb
<% restaurants.each do |restaurant| %>
  <tr>
    <td class="border p-2"><%= restaurant.name%></td>
    <td class="border p-2"><%= restaurant.location%></td>
    <td class="border p-2 text-center">
      <div id="vote_column_<%= restaurant.id %>">
        <%= render partial: 'vote_results', locals: { restaurant: restaurant } %>
      </div>
    </td>
    <td class="border p-2 flex justify-center">
      <% if user_signed_in? %>
        <%= button_to "Will Split", { controller: "restaurants", action: "vote", id: restaurant.id, vote: true }, method: :post, class: "format-button mr-1" %>
        <%= button_to "Won't Split", { controller: "restaurants", action: "vote", id: restaurant.id, vote: false }, method: :post, class: "format-button" %>
      <% else %>
        <%= button_tag "Will Split", class: "format-button bg-gray-800 mr-1", disabled: true, title: "Please sign in to vote" %>
        <%= button_tag "Won't Split", class: "format-button bg-gray-800", disabled: true, title: "Please sign in to vote" %>
      <% end %>
    </td>
    <td class="border p-2 text-center">
      <div class="flex justify-center items-center">
        <%= link_to "Show", restaurant, class: "format-button mr-2" %>
        <% if user_signed_in? %>
          <%= link_to "Edit", edit_restaurant_path(restaurant), class: "format-button mr-2" %>
          <% favorite = current_user.favorites.find_by(restaurant_id: restaurant.id) %>
          <% if favorite %>
            <%= button_to "", favorite_path(favorite), method: :delete, class: "fa fa-star fa-lg checked ml-2" %>
          <% else %>
            <%= button_to "", favorites_path(restaurant_id: restaurant.id), method: :post, class: "ml-2 fa fa-star fa-lg unchecked" %>
          <% end %>
        <% end %>
      </div>
    </td>
  </tr>
<% end %>

app/views/restaurants/_search_form.html.erb
<div class="flex justify-between items-center">
  <%= form_with url: restaurants_path, method: :get do |form| %>
    <%= form.text_field :search, placeholder: "Search by name or location", class: "mr-2 rounded-lg py-3 px-5 bg-white text-gray-800 block font-medium", style: "display: inline-block;" %>
    <%= form.submit "Search", class: "format-button" %>
  <% end %>
</div>

app/views/restaurants/_vote_results.html.erb
<% will_split_count = restaurant.votes.where(vote: true).count %>
<% wont_split_count = restaurant.votes.where(vote: false).count %>

<%= will_split_count %>:<%= wont_split_count %>

app/views/restaurants/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing Restaurant</h1>

  <%= render "form", restaurant: @restaurant, readonly: false %>

  <%= link_to "Show this restaurant", @restaurant, class: "format-button" %>
  <%= link_to "Back to restaurants", restaurants_path, class: "format-button" %>
</div>

app/views/restaurants/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Restaurants</h1>
  </div>

  <div class="flex justify-between items-center mt-5">
    <%= render partial: 'search_form', locals: { restaurants: @restaurants } %>
    <% if user_signed_in? %>
      <%= link_to "New restaurant", new_restaurant_path, class: "format-button" %>
    <% end %>
  </div>

  <table class="w-full border-collapse border mt-5 mb-10">
    <thead>
      <tr>
        <th class="border p-2">Name</th>
        <th class="border p-2">Location</th>
        <th class="border p-2">Will Split:<br>Won't Split</th>
        <th class="border p-2">
          <% if user_signed_in? %>
            Vote
          <% else %>
            Log in to Vote
          <% end %>
        </th>
        <th class="border p-2">Action</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'restaurant_table', locals: { restaurants: @restaurants } %>
    </tbody>
  </table>
</div>

app/views/restaurants/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New Restaurant</h1>

  <%= render "form", restaurant: @restaurant, readonly: false %>

  <%= link_to "Back to restaurants", restaurants_path, class: "format-button" %>
</div>

app/views/restaurants/show.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <h2 class="font-bold text-4xl">Viewing Restaurant</h2>

    <%= render "form", restaurant: @restaurant, readonly: true %>

    <% if user_signed_in? %>
      <%= link_to "Edit this restaurant", edit_restaurant_path(@restaurant), class: "format-button" %>
    <% end %>
    <%= link_to "Back to restaurants", restaurants_path, class: "format-button" %>
  </div>
  <br>
  <br>
  <br>
  <div class="mx-auto">

    <h2 class="font-bold text-4xl">Comments</h2>

    <table class="w-full border-collapse border mt-5 mb-10">
      <thead>
        <tr>
          <th class="border p-2">User</th>
          <th class="border p-2">Comment</th>
          <th class="border p-2">Action</th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'comments/comment_table', locals: { comments: @restaurant.comments, profile: false } %>
      </tbody>
    </table>

    <% if user_signed_in? %>
      <%= link_to "Add Comment", new_comment_path(restaurant_id: @restaurant.id), class: "format-button mb-5" %>
    <% end %>
  </div>

</div>

app/views/restaurants/vote.turbo_stream.erb
<%= turbo_stream.replace "vote_column_#{params[:id]}" do %>
  <%= render partial: 'vote_results', locals: { restaurant: @restaurant } %>
<% end %>