config/routes.rb
Rails.application.routes.draw do
  resources :favorites
  get 'profile/show'
  resources :comments
  resources :votes
  devise_for :users
  root 'restaurants#index', as: 'restaurants_index'

  resources :restaurants do
    post 'vote', on: :member
  end
end

app/views/layouts/_navbar.html.erb
<div class="flex">
  <% unless current_page?(restaurants_path) %>
    <%= link_to "Home", restaurants_path, class: "format-button", style: "margin-right: 10px;" %>
  <% end %>
  <% if user_signed_in? %>
    <% unless current_page?(votes_path) %>
      <%= link_to "Vote History", votes_path, class: "format-button", style: "margin-right: 10px;" %>
    <% end %>
    <% unless current_page?(profile_show_path) %>
      <%= link_to "Profile", profile_show_path, class: "format-button", style: "margin-right: 10px;" %>
    <% end %>
    <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "format-button" %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, class: "format-button", style: "margin-right: 10px;" %>
    <%= link_to "Login", new_user_session_path, class: "format-button", style: "margin-right: 10px;" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplitTheCheck</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <header class="header-box flex justify-between items-center">
      <h1 class="text-3xl font-bold">Split the Check</h1>
      <%= render 'layouts/navbar' %>
    </header>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>